name: camera_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  camera_camera: ^2.0.2
  cupertino_icons: ^1.0.2
  # external_path: any
  # file_picker: 5.2.2
  # fluro: ^2.0.5
  flutter:
    sdk: flutter
  # flutter_sliding_up_panel: 2.0.1
  get: 4.6.5
  # permission_handler: 10.2.0
  # photo_gallery: ^2.0.2
  # photo_view: 0.14.0
  share_plus: any
  # sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
