name: camera_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  whatsapp_camera: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
